spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 54720279139-0nrs5e3mej1b9f15rh6pfhebnh8ub403.apps.googleusercontent.com
            client-secret: ysNIEDAh9_BmmT827D2Xm0Li
            scope: profile,email
#          naver:
#            client-id: 7aWy98Ywds8IV1NEXUAL
#            client-secret: fa1vHElxst
#            redirect-url: {baseUrl}/{action}/oauth2/code/{registrationId}
#            authorization_grant_type: authorization_code
#            scope: name,email,profile_image
#            client-name: Naver
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response